---
backend:
  name: github
  repo: integrated-solutions-nyc/integrated-solutions-nyc.github.io
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
